# Generated by Django 5.0.6 on 2024-07-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tolldetails',
            old_name='cost',
            new_name='contactnumber',
        ),
        migrations.RenameField(
            model_name='tolldetails',
            old_name='endpoint',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='tolldetails',
            old_name='startpoint',
            new_name='selectplan',
        ),
        migrations.RenameField(
            model_name='tolldetails',
            old_name='tickettype',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='tolldetails',
            old_name='tollnumber',
            new_name='ticket',
        ),
        migrations.AddField(
            model_name='tolldetails',
            name='vehiclnumber',
            field=models.CharField(default='', max_length=10),
        ),
    ]
