# Generated by Django 5.0.6 on 2024-07-11 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_rename_cost_tolldetails_contactnumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tolldetails',
            old_name='quantity',
            new_name='nhnumber',
        ),
        migrations.RenameField(
            model_name='tolldetails',
            old_name='source',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='tolldetails',
            old_name='ticket',
            new_name='vehiclenumber',
        ),
        migrations.RenameField(
            model_name='tolldetails',
            old_name='vehiclnumber',
            new_name='vehicletype',
        ),
    ]
