# Generated by Django 5.0.6 on 2024-07-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_rename_quantity_tolldetails_nhnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='paydetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardaccepted', models.CharField(default='', max_length=10)),
                ('nameoncard', models.CharField(default='', max_length=10)),
                ('cardnumber', models.CharField(default='', max_length=10)),
                ('amount', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
